version: '3.7'

services:
    api-qa-challenge-application:
        build:
            context: .
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
        env_file:
            - .env
